DROP TABLE IF EXISTS Account;
CREATE TABLE Account(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
Type VARCHAR(20) NOT NULL,
Date DATETIME NOT NULL,
Item VARCHAR(20) NOT NULL,
Money INT NOT NULL,
Remark VARCHAR(100) NOT NULL,
User VARCHAR(20) NOT NULL,
Color INT NULL
);


DROP TABLE IF EXISTS Source;
CREATE TABLE Source(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
Type VARCHAR(20) NOT NULL,
Item VARCHAR(20) NOT NULL
);


DROP TABLE IF EXISTS Budget;
CREATE TABLE Budget(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
User VARCHAR(20) NOT NULL,
Year INT NOT NULL,
Month INT NOT NULL,
Item VARCHAR(20) NOT NULL,
Budget INT NULL
);
foo